// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNEJCiRXSyK2gtVdmwQ8_m9Ck8RQc_7QY',
    appId: '1:786268876799:web:c70461b16c75a7a45201ca',
    messagingSenderId: '786268876799',
    projectId: 'seniorsemdatabase',
    authDomain: 'seniorsemdatabase.firebaseapp.com',
    storageBucket: 'seniorsemdatabase.firebasestorage.app',
    measurementId: 'G-C6GE8GHYP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRj_jiEyc0qGmAotoBm-p3rXNsSWsyGw',
    appId: '1:786268876799:android:0ec18c10c61958775201ca',
    messagingSenderId: '786268876799',
    projectId: 'seniorsemdatabase',
    storageBucket: 'seniorsemdatabase.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6ArQy5t-LZzv5-3Q3qXjWq04c6q7whU',
    appId: '1:786268876799:ios:122ecdae1b5a15145201ca',
    messagingSenderId: '786268876799',
    projectId: 'seniorsemdatabase',
    storageBucket: 'seniorsemdatabase.firebasestorage.app',
    iosBundleId: 'com.example.seniorSeminarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNEJCiRXSyK2gtVdmwQ8_m9Ck8RQc_7QY',
    appId: '1:786268876799:web:6be2fd5cd7c7df7f5201ca',
    messagingSenderId: '786268876799',
    projectId: 'seniorsemdatabase',
    authDomain: 'seniorsemdatabase.firebaseapp.com',
    storageBucket: 'seniorsemdatabase.firebasestorage.app',
    measurementId: 'G-X9ZN13H77R',
  );
}
